### ISSUE TITLE
OneDrive has a kind of syncing issue in ChromeOS

### ISSUE THREAD

**Issue by MinGyu1000** [rooey/chromeos-filesystem-onedrive#18] opened 2015-10-29 09:03 UTC
Steps to reproduce the problem 
1. make a OneNote file in OneDrive
2. try to sync OneDrive files on your chrome book

Message is poped up like below.
"Some operations are taking longer than expected. Do you want to abort them?" 
And the progress bar is keeping working even if I clicked 'Abort' button.
refer the attached screenshot.
![screenshot 2015-10-15 at 1 56 15 pm](https://cloud.githubusercontent.com/assets/15376718/10814162/5b56f2de-7e67-11e5-88d1-e5d6e4e2886a.png)

**Comment by SynfulEsque** [comment] 2015-11-03 18:41
This has been a constant issue with the OneDrive File System, at least looking at the other issues, and reviews (Issue since July). It is probably the same reason that the extension has issues loading files overall. I'm going to go out on a limb, and say that the OneDrive API has changed, and that this has not been updated for those changes (just my guess).

Considering how many different projects the developer is taking care of, I'm sure he doesn't have time to rewrite the project. I'm also sure if he was to change the license to an Open Source license, someone would be more than happy to contribute changes to fix the project. Otherwise, someone else is just going to write a new one all together, because this project is currently worthless.

**Comment by rooey** [comment] 2017-11-03 16:38
Duplicate of #14

**Closed** 2018-01-10 14:10 UTC

**Comment by 3DEsprit** [comment] 2018-01-10 18:45
That's awesome to see! Thank you!

**Comment by rooey** [comment] 2018-01-10 18:56
:)
