### ISSUE TITLE
Getting Abort message constantly

### ISSUE THREAD

**Issue by GaaraPrime** [rooey/chromeos-filesystem-onedrive#25] opened 2018-03-27 22:57 UTC
It won't run. Constantly told it isn't responding, and to Abort. I think I've seen this posted elsewhere. 

Is there a fix coming soon? Is there a paid version that will resolve this issue (don't mind paying for the app it works).

Cheers.

**Comment by dmcgitit** [comment] 2018-04-02 16:37
I am having this issue as well, it was working perfectly yesterday when I installed it, until I shut my chromebook down and restarted. Please advise!

**Comment by logan-markewich** [comment] 2018-05-05 00:56
Just got an asus C302 and am having the same issue as well. Haven't found a solution anywhere online :/

**Comment by dmcgitit** [comment] 2018-05-05 01:06
I removed it, went with Google drive, no issues now

**Comment by logan-markewich** [comment] 2018-05-05 18:46
Well when you have 1TB storage on onedrive, I'd rather use that lol

**Comment by rooey** [comment] 2018-05-05 20:38
Duplicate of #23

**Closed by rooey** 2018-05-05 20:38 UTC
