### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mimeType' of undefined (v 1.0.4)

### ISSUE THREAD

**Issue by cottonwool** [rooey/chromeos-filesystem-onedrive#17] opened 2015-10-04 10:41 UTC
Hi Yoichiro,

Thanks for your great work on your free file-system utilities.

The file system mounted OK.

It can read the top level directory and some of the next level directories without problem.

I do get the popup "Some operations are taking longer than expected. Do you want to abort them?"

When I try to read the contents of the directory "Documents" it just hangs and when I look at the console I see the error.

From the console it reads the directories within the "Documents" directory:

Object {isDirectory: true, name: "XxxxXxxxxx", size: 249431, modificationTime: Tue Jul 28 2015 01:19:40 GMT+0100 (BST)}isDirectory: truemodificationTime: Tue Jul 28 2015 01:19:40 GMT+0100 (BST)name: "XxxxXxxxxx"size: 249431__proto__: Object
background.js:582 Object {isDirectory: true, name: "XX", size: 2469148, modificationTime: Fri Aug 28 2015 23:26:20 GMT+0100 (BST)}
background.js:582 Object {isDirectory: true, name: "XxxXxxxxx", size: 77190321, modificationTime: Tue Jul 28 2015 01:42:54 GMT+0100 (BST)}
background.js:582 Object {isDirectory: true, name: "Xxxxx Xxxxx", size: 123943, modificationTime: Sun Oct 04 2015 11:17:40 GMT+0100 (BST)}isDirectory: truemodificationTime: Sun Oct 04 2015 11:17:40 GMT+0100 (BST)name: "Xxxxx Xxxxx"size: 123943__proto__: Object

Then we get to the first file in the directory:

background.js:582 Object {isDirectory: false, name: "Fuel Consumption XXnn XXX.xlsx", size: 61877, modificationTime: Tue Jul 21 2015 14:58:59 GMT+0100 (BST), mimeType: "application/vnd.ms-excel.12"}
background.js:580 Uncaught TypeError: Cannot read property 'mimeType' of undefined

The other folders do contain spreadsheets (.xslx), MS-Word docs (.docx), pdfs,  Powerpoints, videos, images, etc.

Is there anything I can do to help?

Regards,

Mark.

**Comment by rooey** [comment] 2017-11-03 16:39
Duplicate of #18

**Closed** 2018-01-10 14:09 UTC
